#
#
#
#
#

# Get access token
POST http://localhost/api/v2/auth/login

###
# Try to access (only with valid token)
GET http://localhost/api/v2/mongo/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmVvbmd3b28iLCJpYXQiOjE2MDExNzI5NTksImV4cCI6MTYwMTE3MzAxOX0.tjChwKPql3IQav7opBiio5TZTEKHXumlo4XNV51Z3jU


