// Dialog
export const SET_DIALOG = "[DIALOG] SET_DIALOG";
export const OFF_DIALOG = "[DIALOG] OFF_DIALOG";
// 
export const SET_PAGE="[PAGE] SET_PAGE";
export const SET_LANGUAGE="[PAGE] SET_LANGUAGE";
export const SET_IS_SIGNED_IN="[PAGE] SET_IS_SIGNED_IN";
export const SET_USER="[USER] SET_USER";
export const SET_LANGUAGES="[USER] SET_LANGUAGES";
// languages
export const SET_ADD_WORD_LANG_PREF="[LANGUAGES] SET_ADD_WORD_LANG_PREF";
export const SET_ADDED_WORDS_COUNT = "[LANGUAGES] SET_ADDED_WORDS_COUNT" //
export const SET_DELETED_WORDS_COUNT = "[LANGUAGES] SET_DELETED_WORDS_COUNT" //
export const INCREMENT_ADDED_WORDS_COUNT = "[LANGUAGES] INCREMENT_ADDED_WORDS_COUNT" //
export const INCREMENT_DELETED_WORDS_COUNT = "[LANGUAGES] INCREMENT_DELETED_WORDS_COUNT" //
// years
export const SET_YEARS="[YEARS] SET_YEARS";
export const ADD_YEARS="[YEARS] ADD_YEARS";
export const DELETE_ONE_YEAR="[YEARS] DELETE_ONE_YEAR"
// words
export const ADD_CHUNK_INTO_DATA="[WORDS] ADD_WORDS_INTO_DATA";
export const ADD_ONE_WORD_INTO_DATA="[WORDS] ADD_ONE_WORD_INTO_DATA";
export const DELETE_ONE_WORD_FROM_DATA="[WORDS] DELETE_ONE_WORD_FROM_DATA"
// snackbar
export const SET_SNACKBAR="[SNACKBAR] SET_SNACKBAR";
export const OFF_SNACKBAR="[SNACKBAR] OFF_SNACKBAR"