export const SET_DIALOG = "[DIALOG] SET_DIALOG";
export const SET_PAGE="[PAGE] SET_PAGE";
export const SET_LANGUAGE="[PAGE] SET_LANGUAGE";
export const SET_IS_SIGNED_IN="[PAGE] SET_IS_SIGNED_IN";
export const SET_USER="[USER] SET_USER";
export const SET_LANGUAGES="[USER] SET_LANGUAGES";
export const SET_ADD_WORD_LANG_PREF="[WORDS] SET_ADD_WORD_LANG_PREF";
export const SET_YEARS="[WORDS] SET_YEARS";
export const ADD_YEARS="[WORDS] ADD_YEARS";
// words
export const ADD_CHUNK_INTO_DATA="[WORDS] ADD_WORDS_INTO_DATA";
export const ADD_ONE_WORD_INTO_DATA="[WORDS] ADD_ONE_WORD_INTO_DATA";
