export const SET_DIALOG = "SET_DIALOG";
export const SET_PAGE="SET_PAGE";
export const SET_LANGUAGE="SET_LANGUAGE";
export const SET_IS_SIGNED_IN="SET_IS_SIGNED_IN";
export const SET_USER="SET_USER";
export const SET_LANGUAGES="SET_LANGUAGES";
export const SET_ADD_WORD_LANG_PREF="SET_ADD_WORD_LANG_PREF";
export const SET_YEARS="SET_YEARS";
export const ADD_YEARS="ADD_YEARS";
// words
export const ADD_CHUNK_INTO_DATA="ADD_WORDS_INTO_DATA";
export const ADD_ONE_WORD_INTO_DATA="ADD_ONE_WORD_INTO_DATA";
export const INSERT_INTO_INDEX="INSERT_INTO_INDEX";